os:
- linux
- osx
language: nix
sudo: required
git:
  depth: 4
env:
  global:
    secure: b37C7eFVGN1QUy2J+3ok9tBbjK0Ubi/rWxRrI7nlfRckc+4pp+OiP0CcFJJcDmkXOkvJoY0DAlMqRf3iiyAPFNQvyYPBnyW5y/JNHoMMyly3ZYgVSlJt3K+upSNRlY4pQb+hKSKSx65PPztFCxe4iH4Ho0uhvoIHJuTbwyJWk79Py6S6dkevhl3ZtKUFCbGpNoOAMRZt6Upyqq2rx3RudYBafYA8U+bRtrmBZFPXRjsqCJ9sGKAy99v9upH7tORDvnDLUSA5gv+l00MctFSdPF0b2yl3g7tDA7oChiJaQjM11xWqdTdw5YxfRr3eoQ4RSqLBMHkpuwPW7s6XA3V+Cl4vnP5lmC/fpRXnzA0kbfjGTMwFD4CI2Aku9M2sDj4UhWWEyNdUDJdOycnPry6H5egyi9d8IG6z84Wb7C3mHVY53n84YD8tuLkd9s7zUDN3oTzWIc1KiSm8IAzoqtkYq25kLGvu7PXRqXkzMTJfK0eTXJoDDzNzp6kdW+v+IC94cS1J1XkG6DgGEjyX2EU3YIjrmwRKq858TyQn8X3J3mSGfBhAaoXsFw/z1P3hvQ/EhVaynaAni6o1oOqOmLJmwK4oBvl+YmHcP9RNnmUT1kiOg51K5VFKgMX/8qFLrwzVJTYzJH9kNlk5VTN/O5vKfnamW0sDX7yHkxOhw39k5q0=
  matrix: 
before_script:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- sudo mkdir -p /etc/nix
- echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
- sudo launchctl kickstart -k system/org.nixos.nix-daemon || true
script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- cachix use simple-ltl
- if [ ! "$CACHIX_SIGNING_KEY" = "" ]; then cachix push simple-ltl --watch-store&
  fi
- if [ ! "$CACHIX_SIGNING_KEY" = "" ]; then nix-build -Q | cachix push simple-ltl;
  else nix-build -Q; fi
branches:
  only:
  - master
